CREATE TABLE `countries` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text,
  `population` DOUBLE,
  `renewable_energy_percentage` DOUBLE,
  `cancer_deaths_per_hundred_thousand` DOUBLE,
  `heart_disease_deaths_per_hundred_thousand` DOUBLE,
  `diarrhoea_deaths_per_hundred_thousand` DOUBLE,
  `diabetes_death_rate_per_hundred_thousand` DOUBLE,
  `drug_related_deaths_per_hundred_thousand` DOUBLE,
  `home_ownership_rate` DOUBLE,
  `homelessness_rate` DOUBLE,
  `litres_of_alcohol_per_person_per_year` DOUBLE,
  `obesity_percentage` DOUBLE,
  `covid_deaths_per_hundred_thousand` DOUBLE,
  `unemployment` DOUBLE,
  `life_expectancy` DOUBLE,
  `co2_emissions` DOUBLE,
  `infant_mortality` DOUBLE,
  `adolescent_birth_rate_per_thousand` DOUBLE,
  `human_inequality_coefficient` DOUBLE,
  `gender_inequality_index` DOUBLE,
  `gross_enrolement_tertiary_education_ratio` DOUBLE,
  `mean_years_of_schooling` DOUBLE,
  `natural_resource_depletion` DOUBLE,
  `prison_population_per_hundred_thousand` DOUBLE,
  `intentional_homicide_rate_per_hundred_thousand` DOUBLE,
  `research_and_development_expenditure_percent_of_gpd` DOUBLE,
  `percentage_women_in_parliament` DOUBLE,
  `suicide_rate_male` DOUBLE,
  `suicide_rate_female` DOUBLE,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
  )ENGINE=InnoDB AUTO_INCREMENT=6;

