CREATE TABLE `countries` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text,
  `cancer_deaths_per_hundred_thousand` DOUBLE,
  `heart_disease_deaths_per_hundred_thousand` DOUBLE,
  `diarrhoea_deaths_per_hundred_thousand` DOUBLE,
  `diabetes_death_rate_per_hundred_thousand` DOUBLE,
  `prob_death_cardio_vascular_cancer_diabetes_respiratory` DOUBLE,
  `drug_related_deaths_per_hundred_thousand` DOUBLE,
  `gov_benefits_for_drug_use_disorder_data` DOUBLE,
  `home_ownership_rate` DOUBLE,
  `homelessness_rate` DOUBLE,
  `covid_deaths_per_hundred_thousand` DOUBLE,
  `unemployment` DOUBLE,
  `life_expectancy_male` DOUBLE,
  `life_expectancy_female` DOUBLE,
  `co2_emissions` DOUBLE,
  `post_secondary_enrollment_female` DOUBLE,
  `post_secondary_enrollment_male` DOUBLE,
  `infant_mortality` DOUBLE,
  `threatened_species` DOUBLE,
  `adolescent_birth_rate_per_thousand` DOUBLE,
  `human_inequality_coefficient` DOUBLE,
  `health_expenditure_percentage_gdp` DOUBLE,
  `fossil_fuel_consumption_percentage_of_total_energy_consumption` DOUBLE,
  `gender_inequality_index` DOUBLE,
  `gross_enrolement_tertiary_education_ratio` DOUBLE,
  `homicide_rate_per_hundred_thousand` DOUBLE,
  `mean_years_of_schooling` DOUBLE,
  `natural_resource_depletion` DOUBLE,
  `safe_sanitation_services` DOUBLE,
  `prison_population_per_hundred_thousand` DOUBLE,
  `research_and_development_expenditure_percent_of_gpd` DOUBLE,
  `percentage_women_in_parliament` DOUBLE,
  `suicide_rate_male` DOUBLE,
  `suicide_rate_female` DOUBLE,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
  )ENGINE=InnoDB AUTO_INCREMENT=6;

